name: Deploy to NAS via ngrok

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to NAS
        run: |
          curl -v -X POST \
            -H "X-DEPLOY-TOKEN: my-secret-token" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main"}' \
            https://702af93e259c.ngrok-free.app/deploy
